import { useState, useEffect } from 'react';
import { LineChart, Line, BarChart, Bar, PieChart, Pie, Cell, XAxis, YAxis, CartesianGrid, Tooltip as RechartsTooltip, ResponsiveContainer, Legend } from 'recharts';
import { motion } from 'framer-motion';
import CountUp from 'react-countup';
import API from '../api';

const COLORS = ['#ef4444', '#f59e0b', '#10b981']; // Red (High), Yellow (Medium), Green (Low)

// Variants for staggered children animations
const containerVariants = {
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: {
      staggerChildren: 0.2
    }
  }
};

const itemVariants = {
  hidden: { y: 20, opacity: 0 },
  visible: {
    y: 0,
    opacity: 1,
    transition: {
      duration: 0.5,
      ease: "easeOut"
    }
  }
};

function AnalyticsTab() {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchAnalytics();
  }, []);

  const fetchAnalytics = async () => {
    try {
      const res = await API.get("/analytics");
      setData(res.data);
    } catch (error) {
      console.error("Failed to fetch analytics", error);
    } finally {
      setLoading(false);
    }
  };

  if (loading) {
    return <div style={{ padding: '2rem', textAlign: 'center', color: 'var(--text-secondary)' }}>Loading system analytics...</div>;
  }

  if (!data || data.total_predictions === 0) {
    return (
      <motion.div 
        initial={{ opacity: 0, scale: 0.95 }}
        animate={{ opacity: 1, scale: 1 }}
        className="glass-card" style={{ padding: '2rem', textAlign: 'center' }}
      >
        <h2 style={{ color: 'var(--text-primary)' }}>No Data Yet</h2>
        <p style={{ color: 'var(--text-secondary)' }}>Make some dynamic pricing predictions to see your dashboard light up!</p>
      </motion.div>
    );
  }

  return (
    <motion.div 
      variants={containerVariants}
      initial="hidden"
      animate="visible"
      className="glass-card" 
      style={{ padding: '2rem' }}
    >
      <motion.div variants={itemVariants} style={{ marginBottom: '2rem', borderBottom: '1px solid var(--border-color)', paddingBottom: '1rem' }}>
        <h2 style={{ margin: 0, textAlign: 'left', color: 'var(--text-primary)' }}>📈 System Overview</h2>
        <p style={{ color: 'var(--text-secondary)', marginTop: '0.5rem' }}>
          Real-time metrics aggregating all dynamic predictions generated by your ML engine.
        </p>
      </motion.div>

      <motion.div variants={containerVariants} style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '1.5rem', marginBottom: '3rem' }}>
        <motion.div variants={itemVariants} style={{ padding: '1.5rem', background: 'rgba(59, 130, 246, 0.1)', border: '1px solid rgba(59, 130, 246, 0.3)', borderRadius: '12px' }}>
          <h4 style={{ color: 'var(--text-secondary)', margin: '0 0 0.5rem 0' }}>Total API Calls</h4>
          <p style={{ fontSize: '2rem', fontWeight: 'bold', color: '#60a5fa', margin: 0 }}>
            <CountUp end={data.total_predictions} duration={2} separator="," />
          </p>
        </motion.div>
        
        <motion.div variants={itemVariants} style={{ padding: '1.5rem', background: 'rgba(16, 185, 129, 0.1)', border: '1px solid rgba(16, 185, 129, 0.3)', borderRadius: '12px' }}>
          <h4 style={{ color: 'var(--text-secondary)', margin: '0 0 0.5rem 0' }}>Average Fare (₹)</h4>
          <p style={{ fontSize: '2rem', fontWeight: 'bold', color: '#34d399', margin: 0 }}>
            ₹<CountUp end={data.average_price} decimals={2} duration={2.5} separator="," />
          </p>
        </motion.div>

        <motion.div variants={itemVariants} style={{ padding: '1.5rem', background: 'rgba(245, 158, 11, 0.1)', border: '1px solid rgba(245, 158, 11, 0.3)', borderRadius: '12px' }}>
          <h4 style={{ color: 'var(--text-secondary)', margin: '0 0 0.5rem 0' }}>Avg Surge Applied</h4>
          <p style={{ fontSize: '2rem', fontWeight: 'bold', color: '#fbbf24', margin: 0 }}>
            <CountUp end={data.average_surge} decimals={2} duration={2} />x
          </p>
        </motion.div>
      </motion.div>

      <motion.div variants={containerVariants} style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(400px, 1fr))', gap: '2rem' }}>
        
        <motion.div variants={itemVariants} style={{ background: 'rgba(30, 41, 59, 0.4)', padding: '1.5rem', borderRadius: '12px', border: '1px solid var(--border-color)' }}>
          <h3 style={{ marginBottom: '1.5rem', color: 'var(--text-primary)' }}>Recent Price Trends</h3>
          <div style={{ width: '100%', height: 300 }}>
            <ResponsiveContainer width="100%" height="100%">
              <LineChart data={data.recent_trends} margin={{ top: 5, right: 20, bottom: 5, left: 0 }}>
                <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.05)" />
                <XAxis dataKey="time" stroke="var(--text-secondary)" />
                <YAxis stroke="var(--text-secondary)" />
                <RechartsTooltip 
                  contentStyle={{ backgroundColor: 'rgba(15, 23, 42, 0.95)', border: '1px solid rgba(255,255,255,0.2)', borderRadius: '12px', color: '#fff', boxShadow: '0 8px 32px 0 rgba(0,0,0,0.5)', padding: '12px' }}
                  itemStyle={{ color: '#fff', fontWeight: '500', padding: '4px 0' }}
                  labelStyle={{ color: 'var(--text-secondary)', marginBottom: '8px' }}
                />
                <Legend />
                <Line type="monotone" dataKey="price" name="Fare (₹)" stroke="#3b82f6" strokeWidth={3} activeDot={{ r: 8, strokeWidth: 2, stroke: '#fff' }} />
                <Line type="monotone" dataKey="surge" name="Surge Multiplier" stroke="#f59e0b" strokeWidth={3} activeDot={{ r: 8, strokeWidth: 2, stroke: '#fff' }} />
              </LineChart>
            </ResponsiveContainer>
          </div>
        </motion.div>
        
        <motion.div variants={itemVariants} style={{ background: 'rgba(30, 41, 59, 0.4)', padding: '1.5rem', borderRadius: '12px', border: '1px solid var(--border-color)' }}>
          <h3 style={{ marginBottom: '1.5rem', color: 'var(--text-primary)' }}>Demand Distribution</h3>
          <div style={{ width: '100%', height: 300 }}>
            <ResponsiveContainer width="100%" height="100%">
              <PieChart>
                <Pie
                  data={data.demand_distribution}
                  cx="50%"
                  cy="50%"
                  innerRadius={60}
                  outerRadius={100}
                  paddingAngle={5}
                  dataKey="value"
                  animationDuration={1500}
                  animationEasing="ease-out"
                >
                  {data.demand_distribution.map((entry, index) => (
                    <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                  ))}
                </Pie>
                <RechartsTooltip 
                  contentStyle={{ backgroundColor: 'rgba(15, 23, 42, 0.95)', border: '1px solid rgba(255,255,255,0.2)', borderRadius: '12px', color: '#fff', boxShadow: '0 8px 32px 0 rgba(0,0,0,0.5)', padding: '12px' }}
                  itemStyle={{ color: '#fff', fontWeight: '500' }}
                />
                <Legend />
              </PieChart>
            </ResponsiveContainer>
          </div>
        </motion.div>

      </motion.div>
    </motion.div>
  );
}

export default AnalyticsTab;
